version: "3.7"

services:
  web_server: # service name
    image: nginx # image is built with build
    build: ./requirements/nginx
    #configs:
    #  - source: #my_config
    #    target: #/nginx_config
    #    uid: "103"
    #    gid: "103"
    #    mode: 0440
    volumes:
      - web-data:/home/suahn/data/www:rw
    restart: always
    expose: # publish the ports to the linked services of the container
      - "9000"
    ports:
      - "8080:9000/tcp" # host:container
  db:
    image: mariadb
    build: ./requirements/mariadb
    volumes:
      - db-data:/home/suahn/data/mariadb:rw
    restart: always
    env_file: .env
    expose:
      - "3306"
  web:
    image: wordpress
    #build: ./requirements/wordpress
    volumes:
      - web-data:/home/suahn/data/www:rw
    restart: always
    env_file: .env
    expose:
      - "3306"
      - "9000"
    depends_on:
      - web_server
      - db

volumes:
  db-data:
  web-data:
#configs:
# my_config:
#   external: true
#entrypoint: "/usr/sbin/nginx", "-g", "daemon off;"

networks:
  default:
    driver: bridge