version: "3.7"

services:
  nginx: # service name
    #image: nginx # image is built with build
    container_name: nginx
    build: ./requirements/nginx
    volumes:
      - web-data:/var/www/html
    restart: always
    expose: # publish the ports to the linked services of the container
      - "9000"
    ports:
      - "8080:443/tcp" # host:container
    env_file: .env
    extra_hosts:
      - "${DOMAIN_NAME}:127.0.0.1" # created in /etc/hosts
    dns_search:
      - suahn.42.fr
    depends_on:
      - wordpress
    #tty: true
  db:
    #image: mariadb
    container_name: db
    build: ./requirements/mariadb
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    env_file: .env
    expose:
      - "3306"
   #tty: true
  wordpress:
    #image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - web-data:/var/www/html # host:container
    restart: always
    stdin_open: true # -i
    tty: true # -t
    env_file: .env
    expose:
      - "3306"
      - "9000"
    depends_on:
      - db

volumes:
  db-data:
  web-data: # named volume can persist data after restart or remove a container
    #driver: local
    #driver_opts:
    #  o: bind
     # type: none
     # device: /home/suahn/data/www

networks:
  default:
    driver: bridge