version: "3.7"

services:
  nginx: # service name
    #image: nginx # image is built with build
    build: ./requirements/nginx
    #volumes:
    #  - web-data:/home/suahn/data/www:rw
    restart: always
    expose: # publish the ports to the linked services of the container
      - "9000"
    ports:
      - "8080:443/tcp" # host:container
    depends_on:
      - wordpress
    #tty: true
  db:
    #image: mariadb
    build: ./requirements/mariadb
    #volumes:
    #  - db-data:/home/suahn/data/mariadb:rw
    restart: always
    env_file: .env
    expose:
      - "3306"
   #tty: true
  wordpress:
    #image: wordpress
    build: ./requirements/wordpress
 #   volumes:
  #    - web-data:/home/suahn/data/www:rw
    restart: always
    env_file: .env
    expose:
      - "3306"
      - "9000"
    depends_on:
      - db
    #tty: true

#volumes:
#  db-data:
#  web-data:

networks:
  default:
    driver: bridge