version: "3.7"

services:
  nginx: # service name
    image: nginx
    container_name: nginx_c
    build: ./requirements/nginx
    volumes:
      - web-data:/var/www/html
    restart: unless-stopped # Always restart unless the developers forcibly stop the process
    expose: # publish the ports to the linked services of the container
      - "9000"
    ports:
      - "443:443/tcp" # host:container
    env_file: .env
    #extra_hosts:
    #  - "suahn.42.fr:127.0.0.1" # created in /etc/hosts
    depends_on:
      - wordpress
  mariadb:
    image: mariadb
    container_name: mariadb_c
    build: ./requirements/mariadb
    volumes:
      - db-data:/var/lib/mysql
    restart: unless-stopped
    env_file: .env
    expose:
      - "3306"
      - "8080"
  wordpress:
    image: wordpress
    container_name: wordpress_c
    build: ./requirements/wordpress
    volumes:
      - web-data:/var/www/html
    restart: unless-stopped
    stdin_open: true # i
    tty: true # t
    env_file: .env
    expose:
      - "3306"
      - "9000"
      - "6379"
    depends_on:
      - mariadb
  adminer:
    image: adminer
    container_name: adminer_c
    build: ./requirements/bonus/adminer
    volumes:
      - web-data:/var/www/html
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - "8080:8080/tcp"
    depends_on:
      - mariadb

volumes:
  db-data:
    name: db-data
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/suahn/data/db

  web-data: # named volume can persist data after restart or remove a container
    name: web-data
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/suahn/data/web

networks:
  default:
    driver: bridge