version: "3.7"

services:
  server: # service name
    image: nginx # image is built with build
    build: ./requirements/nginx
    #configs:
    #  - source: #my_config
    #    target: #/nginx_config
    #    uid: "103"
    #    gid: "103"
    #    mode: 0440
    volumes:
      - web-volume:/home/suahn/data:rw
    expose: # publish the ports to the linked services of the container
      - "9000"
  web:
    image: wordpress
    build: ./requirements/wordpress
    volumes:
      - web-volume:/home/suahn/data:rw
    expose:
      - "3306"
      - "9000"
    depends_on:
      - nginx
      - maraidb
  db:
    image: mariadb
    build: ./requirements/mariadb
    volumes:
      - db-volume:/home/suahn/data:rw
    expose:
      - "3306"

#configs:
# my_config:
#   external: true

entrypoint:

networks:
  default:
    driver: bridge

env_file: .env

ports:
  - "443:9000/tcp" # host:container