version: "3.7"

services:
  nginx: # service name
    container_name: nginx
    build: ./requirements/nginx
    volumes:
      - web-data:/var/www/html
    restart: unless-stopped # Always restart unless the developers forcibly stop the process
    expose: # publish the ports to the linked services of the container
      - "9000"
    ports:
      - "443:443/tcp" # host:container
    env_file: .env
    extra_hosts:
      - "${DOMAIN_NAME}:127.0.0.1" # created in /etc/hosts
    dns_search:
      - suahn.42.fr
    depends_on:
      - wordpress
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - db-data:/var/lib/mysql
    restart: unless-stopped
    env_file: .env
    expose:
      - "3306"
      - "8080"
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - web-data:/var/www/html # host:container
    restart: unless-stopped
    stdin_open: true # -i
    tty: true # -t
    env_file: .env
    expose:
      - "3306"
      - "9000"
    depends_on:
      - mariadb
  adminer:
    container_name: adminer
    build: ./requirements/adminer
    volumes:
      - web-data:/var/www/html
    restart: unless-stopped
    stdin_open: true # -i
    tty: true # -t
    ports:
      - "8080:8080/tcp"
    depends_on:
      - mariadb
  redis:
    container_name: redis
    build: ./requirements/redis
    restart: unless-stopped
    stdin_open: true # -i
    tty: true # -t
    ports:
      - "6379:6379/tcp"

volumes:
  db-data:
    name: db-data
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/suahn/data/db

  web-data: # named volume can persist data after restart or remove a container
    name: web-data
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/suahn/data/web

networks:
  default:
    driver: bridge